name: linktodo
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  firebase_core: ^3.4.0
  firebase_analytics: ^11.3.0
  # 追加
  flutter_local_notifications: ^17.2.2
  share_plus: ^7.2.2
  html: ^0.15.4
  http: ^1.2.1
  url_launcher: ^6.3.0
  uuid: ^4.4.2
  intl: ^0.19.0
  google_mobile_ads: ^5.1.0

  # AppsFlyer
  appsflyer_sdk: ^6.14.2
  # IAP
  in_app_purchase: ^3.2.0
  timezone: ^0.9.2
  flutter_native_splash: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  hive_generator: ^2.0.1
  build_runner: ^2.4.11

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansJP-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansJP-Bold.ttf
          weight: 700

flutter_native_splash:
  color: "#FF8C00"
  image: assets/images/splash_icon.png
  color_dark: "#FF8C00"
  image_dark: assets/images/splash_icon.png
  android_12:
    color: "#FF8C00"
    image: assets/images/splash_icon.png
  ios: true
  android: true